Repository hengyoush/kyanos, pull requests merged in 2024-12, with the labels that each got.

#153 feat(filter): support filter traffic by process name
  agent/agent.go
  agent/common/options.go
  bpf/loader/btf.go
  bpf/loader/loader.go
  cmd/root.go
  docs/cn/watch.md
  docs/watch.md
  go.mod
  go.sum
Labels: enhancement, size:L

#155 fix: fix #154
  agent/conn/kern_event_handler.go
Labels: bug, size:XS, bug-fix, test-passed

#163 docs: improve docs highlights root privielge
  README.md
  README_CN.md
  docs/cn/quickstart.md
  docs/quickstart.md
Labels: size:M

#162 157 caught panic when input kyanos watch ssh
  agent/render/watch/watch_render.go
  cmd/watch.go
Labels: bug, size:XS

#167 fix(bpf/gotls): fix #137
  bpf/gotls.bpf.c
Labels: size:XS, bug-fix

#171 fix: Fix the potential out-of-bounds vulnerability in the slice withi…
  agent/protocol/mysql/handler.go
Labels: bug, size:S, lgtm

#173 docs: improve how-to-build docs
  COMPILATION.md
  COMPILATION_CN.md
  docs/cn/how-to-build.md
  docs/how-to-build.md
Labels: documentation, size:L

#181 fix: output logs to file during loading
  agent/agent.go
  agent/render/loader/loader_render.go
  bpf/loader/btf.go
  bpf/loader/loader.go
  common/log.go
  go.sum
Labels: size:M

#182 fix: fix latency filter bug
  agent/conn/record_processor.go
Labels: size:XS, bug-fix

#184 feat: add terminal color check
  agent/agent.go
  common/term.go
Labels: enhancement, size:S

#187 refactor: improve terminal color check
  agent/agent.go
  common/term.go
Labels: size:S

#190 docs: add `git submodule update ...`
  COMPILATION.md
  COMPILATION_CN.md
  docs/cn/how-to-build.md
  docs/how-to-build.md
Labels: size:S

#191 feat: Print osinfo when start failed
  agent/agent.go
Labels: enhancement, size:M

#188 docs: add faq docs
  docs/.vitepress/config.mts
  docs/cn/faq.md
  docs/cn/quickstart.md
  docs/faq.md
  docs/public/missing-color.png
  docs/quickstart.md
Labels: documentation, size:L

#193 docs: wrong url to download the init script
  COMPILATION.md
  COMPILATION_CN.md
  docs/cn/how-to-build.md
  docs/how-to-build.md
Labels: documentation, size:XS

#194 chore: make `go list -m -json all` works to import the project by goland
  go.mod
Labels: size:M, lgtm

#195 chore: ignore `.idea` dir
  .gitignore
Labels: size:XS, lgtm

#198 fix: add rw lock to prevent concurrent map read write
  agent/conn/kern_event_handler.go
Labels: size:M, bug-fix

#199 refactor: remove fatal log
  agent/agent.go
  agent/container.go
  bpf/loader/btf.go
  bpf/loader/container.go
  bpf/loader/loader.go
Labels: size:L

#202 chore: introduce an issues translator
  .github/workflows/issue-translator.yml
Labels: enhancement, size:S, lgtm

#196 feat: introduce a new workflow to verify build script on multi platforms
  .github/workflows/build_verification.yml
  Makefile
  bpf/loader/loader.go
  init_env.sh
Labels: enhancement, size:M, lgtm

#209 chore: init_env cleanup
  init_env.sh
Labels: size:XS, lgtm

#210 fix: supports container-id prefix matching with 12 or more characters
  agent/metadata/container/containerd/containerd.go
  agent/metadata/container/docker/docker.go
Labels: size:XS, lgtm, bug-fix

#211 update FAQ
  docs/cn/faq.md
  docs/faq.md
Labels: documentation, size:S, lgtm

#213 fix(stat): elapsed time is negative
  agent/agent.go
  agent/common/options.go
  agent/conn/processor.go
  agent/render/watch/watch_render.go
  cmd/root.go
Labels: size:M, bug-fix

#215 build: add debugging targets and improve Makefile structure
  Makefile
Labels: enhancement, size:S, lgtm

#220 feat: Introduce more flags to filter HTTP records
  Makefile
  agent/protocol/http.go
  agent/protocol/http_test.go
  bpf/loader/utils.go
  cmd/http.go
  docs/cn/watch.md
  docs/watch.md
Labels: enhancement, size:L, lgtm

#223 docs: add how to add a new protocol docs
  agent/protocol/protocol.go
  docs/.vitepress/config.mts
  docs/cn/how-to-add-a-new-protocol.md
  docs/how-to-add-a-new-protocol.md
  docs/public/protocol-parse-flow.png
Labels: documentation, size:XL

#221 docs: introduce `prettier` and `md-padding` to format all docs
  .prettierignore
  .prettierrc
  CODE_OF_CONDUCT.md
  COMPILATION.md
  COMPILATION_CN.md
  Makefile
  README.md
  README_CN.md
  docs/cn/faq.md
  docs/cn/how-to-add-a-new-protocol.md
  docs/cn/how-to-build.md
  docs/cn/how-to.md
  docs/cn/index.md
  docs/cn/quickstart.md
  docs/cn/stat.md
  docs/cn/watch.md
  docs/cn/what-is-kyanos.md
  docs/faq.md
  docs/how-to-add-a-new-protocol.md
  docs/how-to-build.md
  docs/how-to.md
  docs/index.md
  docs/quickstart.md
  docs/stat.md
  docs/watch.md
  docs/what-is-kyanos.md
  package-lock.json
  package.json
Labels: documentation, size:XXL

#232 fix: add fallback logic for total time when dev in event missed in server side
  agent/analysis/stat.go
  agent/conn/conntrack.go
Labels: size:XS, bug-fix

#222 test: introduce a script to test flag `--comm`
  .github/workflows/test.yml
  testdata/https-request/http_request.go
  testdata/start_http_server.py
  testdata/test_filter_by_comm.sh
Labels: unittest, size:L, lgtm

#234 feat: introduce version cmd
  .github/workflows/release.yml
  .goreleaser.yaml
  cmd/version.go
Labels: enhancement, size:M, lgtm

#236 fix: ssl event at server side can't be captured correctly
  agent/analysis/stat.go
  agent/conn/conntrack.go
  agent/conn/processor.go
  bpf/agent_arm64_bpfel.go
  bpf/agent_x86_bpfel.go
  bpf/agentlagacykernel310_arm64_bpfel.go
  bpf/agentlagacykernel310_x86_bpfel.go
  bpf/data_common.h
  bpf/gen.go
  bpf/gotls_arm64_bpfel.go
  bpf/gotls_x86_bpfel.go
  bpf/gotlslagacykernel310_arm64_bpfel.go
  bpf/gotlslagacykernel310_x86_bpfel.go
  bpf/loader/loader.go
  bpf/openssl102a_arm64_bpfel.go
  bpf/openssl102a_x86_bpfel.go
  bpf/openssl110a_arm64_bpfel.go
  bpf/openssl110a_x86_bpfel.go
  bpf/openssl111a_arm64_bpfel.go
  bpf/openssl111a_x86_bpfel.go
  bpf/openssl111b_arm64_bpfel.go
  bpf/openssl111b_x86_bpfel.go
  bpf/openssl111d_arm64_bpfel.go
  bpf/openssl111d_x86_bpfel.go
  bpf/openssl111j_arm64_bpfel.go
  bpf/openssl111j_x86_bpfel.go
  bpf/openssl300_arm64_bpfel.go
  bpf/openssl300_x86_bpfel.go
  bpf/openssl310_arm64_bpfel.go
  bpf/openssl310_x86_bpfel.go
  bpf/openssl320_arm64_bpfel.go
  bpf/openssl320_x86_bpfel.go
  bpf/openssl323_arm64_bpfel.go
  bpf/openssl323_x86_bpfel.go
  bpf/openssl330_arm64_bpfel.go
  bpf/openssl330_x86_bpfel.go
  bpf/openssl340_arm64_bpfel.go
  bpf/openssl340_x86_bpfel.go
  bpf/pktlatency.bpf.c
  bpf/pktlatency.h
  bpf/prog.go
  bpf/types.go
Labels: size:XL, bug-fix
