Repository hengyoush/kyanos, pull requests merged in 2025-02, with the labels that each got.

#283 fix: fix dnsutils packege can't be found
  .github/workflows/test.yml
Labels: size:XS, bug-fix

#287 BPF Event log translate to English
  bpf/common.go
Labels: documentation, size:XS, lgtm

#292 feat(openssl): support openssl 3.4.1
  agent/uprobe/types.go
Labels: enhancement, size:XS

#290 fix: fix https can't be captured
  bpf/events.go
Labels: size:XS, bug-fix

#293 fix: mysql test failure
  testdata/test_mysql.sh
  testdata/test_side.sh
Labels: size:XS, bug-fix

#284 feat: check pid when attaching uprode.
  agent/agent.go
  agent/uprobe/manager.go
Labels: enhancement, size:M, lgtm

#296 fix: wrong param name
  cmd/root.go
Labels: size:XS, bug-fix

#275 feat: Support MongoDB protocol
  .github/workflows/test.yml
  agent/protocol/decoder.go
  agent/protocol/mongodb/mongodb.go
  agent/protocol/mongodb/mongodb_test.go
  agent/protocol/mongodb/stitcher.go
  agent/protocol/mongodb/types.go
  bpf/common.go
  bpf/protocol_inference.h
  cmd/mongodb.go
  cmd/watch.go
  go.mod
  go.sum
  testdata/test_add_cap_bpf.sh
  testdata/test_gotls.sh
  testdata/test_k8s.yaml
  testdata/test_mongodb.sh
  testdata/test_not_add_cap_bpf.sh
  testdata/test_truncated_data.sh
Labels: enhancement, size:XXL
