Repository hengyoush/kyanos, pull requests merged in 2025-04, with the labels that each got.

#308 Update COMPILATION.md
  COMPILATION.md
Labels: documentation, size:XS

#310 perf: skip unnecessary protocol infer when specify in cmd line
  agent/protocol/dns/filter.go
  agent/protocol/generic_filter.go
  agent/protocol/http.go
  agent/protocol/kafka/filter.go
  agent/protocol/mongodb/mongodb.go
  agent/protocol/mysql/filter.go
  agent/protocol/protocol.go
  agent/protocol/redis..go
  agent/protocol/rocketmq/filter.go
  agent/uprobe/common.go
  bpf/agent_arm64_bpfel.go
  bpf/agent_x86_bpfel.go
  bpf/data_common.h
  bpf/gotls_arm64_bpfel.go
  bpf/gotls_x86_bpfel.go
  bpf/gotlslagacykernel310_arm64_bpfel.go
  bpf/gotlslagacykernel310_x86_bpfel.go
  bpf/loader/loader.go
  bpf/openssl102a_arm64_bpfel.go
  bpf/openssl102a_x86_bpfel.go
  bpf/openssl110a_arm64_bpfel.go
  bpf/openssl110a_x86_bpfel.go
  bpf/openssl111a_arm64_bpfel.go
  bpf/openssl111a_x86_bpfel.go
  bpf/openssl111b_arm64_bpfel.go
  bpf/openssl111b_x86_bpfel.go
  bpf/openssl111d_arm64_bpfel.go
  bpf/openssl111d_x86_bpfel.go
  bpf/openssl111j_arm64_bpfel.go
  bpf/openssl111j_x86_bpfel.go
  bpf/openssl300_arm64_bpfel.go
  bpf/openssl300_x86_bpfel.go
  bpf/openssl310_arm64_bpfel.go
  bpf/openssl310_x86_bpfel.go
  bpf/openssl320_arm64_bpfel.go
  bpf/openssl320_x86_bpfel.go
  bpf/openssl323_arm64_bpfel.go
  bpf/openssl323_x86_bpfel.go
  bpf/openssl330_arm64_bpfel.go
  bpf/openssl330_x86_bpfel.go
  bpf/openssl340_arm64_bpfel.go
  bpf/openssl340_x86_bpfel.go
  bpf/openssl350_arm64_bpfel.go
  bpf/openssl350_x86_bpfel.go
  bpf/pktlatency.bpf.c
  bpf/pktlatency.h
  bpf/protocol_inference.h
Labels: size:L

#311 refactor: replace tp with fentry if possible
  .github/workflows/build_verification.yml
  agent/compatible/type.go
  agent/conn/processor.go
  agent/uprobe/manager.go
  bpf/agent_arm64_bpfel.go
  bpf/agent_x86_bpfel.go
  bpf/agentlagacykernel310_arm64_bpfel.go
  bpf/agentlagacykernel310_x86_bpfel.go
  bpf/loader/loader.go
  bpf/pktlatency.bpf.c
  bpf/prog.go
Labels: size:XXL
