Repository hengyoush/kyanos, pull requests merged in 2025-01, with the labels that each got.

#238 test: wait a longer time to ensure process exec event can be handled
  agent/uprobe/gotls.go
  testdata/test_filter_by_comm.sh
Labels: size:XS

#239 fix: handle MySQL null(/xfb) field correctly
  agent/protocol/mysql/utils.go
Labels: size:S, bug-fix

#240 docs: add debug tips doc
  docs/.vitepress/config.mts
  docs/.vitepress/theme/index.mts
  docs/.vitepress/theme/style/index.css
  docs/.vitepress/theme/style/var.css
  docs/cn/debug-tips.md
  docs/cn/how-to-add-a-new-protocol.md
  docs/debug-tips.md
  docs/how-to-add-a-new-protocol.md
Labels: documentation, size:L

#235 feat: Add json-output params to watch command
  agent/analysis/common/json.go
  agent/render/watch/option.go
  agent/render/watch/watch_render.go
  cmd/watch.go
  docs/.vitepress/config.mts
  docs/cn/json-output.md
  docs/cn/watch.md
  docs/json-output.md
  docs/watch.md
  package-lock.json
Labels: documentation, enhancement, size:L, lgtm

#244 fix(test): fix filter-by-comm.test occasionally failed
  agent/uprobe/manager.go
  bpf/events.go
  bpf/loader/loader.go
  testdata/test_filter_by_comm.sh
Labels: size:M, bug-fix

#243 fix: use tracepoint instead of kprobe to trace skb_copy_datagram_iovec
  agent/compatible/type.go
  bpf/agent_arm64_bpfel.go
  bpf/agent_x86_bpfel.go
  bpf/agentlagacykernel310_arm64_bpfel.go
  bpf/agentlagacykernel310_x86_bpfel.go
  bpf/pktlatency.bpf.c
Labels: enhancement, size:S

#242 feat: check cap privileges instead of `Geteuid` during starting the agent
  .github/workflows/test.yml
  agent/agent.go
  agent/common/permission.go
  go.mod
  go.sum
  testdata/run_cap_bpf_test.sh
  testdata/test_add_cap_bpf.sh
  testdata/test_not_add_cap_bpf.sh
Labels: enhancement, size:L, lgtm

#246 fix: fix mysql protcol parser array index out of range issue and gotls load failed issue
  agent/protocol/mysql/handler.go
  bpf/gotls.bpf.c
Labels: size:XS, bug-fix

#247 user: add command-line options to set perf event buffer size
  agent/agent.go
  agent/common/options.go
  cmd/root.go
Labels: enhancement, size:S, lgtm

#254 feat: Introduce counters to count lost samples in `bpf/events`
  bpf/events.go
Labels: enhancement, size:M, lgtm

#231 feat: support rocketMQ
  .github/workflows/test.yml
  agent/protocol/rocketmq/filter.go
  agent/protocol/rocketmq/language_code.go
  agent/protocol/rocketmq/rocketmq.go
  agent/protocol/rocketmq/types.go
  bpf/agent_arm64_bpfel.go
  bpf/agent_x86_bpfel.go
  bpf/common.go
  bpf/pktlatency.h
  bpf/protocol_inference.h
  cmd/rocketmq.go
  cmd/watch.go
  docs/cn/watch.md
  docs/watch.md
  testdata/rocketmq_producer.py
  testdata/run_e2e.sh
  testdata/test_rocketmq.sh
Labels: enhancement, size:XL, lgtm

#257 feat: support for parsing ipip packet
  agent/agent.go
  agent/analysis/stat.go
  agent/buffer/stream_buffer.go
  agent/common/options.go
  agent/conn/conntrack.go
  agent/conn/first_packet_processor.go
  agent/conn/kern_event_handler.go
  agent/conn/net.go
  agent/conn/processor.go
  agent/metadata/process.go
  agent/render/watch/time_detail.go
  agent/uprobe/common.go
  bpf/agent_arm64_bpfel.go
  bpf/agent_x86_bpfel.go
  bpf/agentlagacykernel310_arm64_bpfel.go
  bpf/agentlagacykernel310_x86_bpfel.go
  bpf/data_common.h
  bpf/events.go
  bpf/gen.go
  bpf/gotls_arm64_bpfel.go
  bpf/gotls_x86_bpfel.go
  bpf/gotlslagacykernel310_arm64_bpfel.go
  bpf/gotlslagacykernel310_x86_bpfel.go
  bpf/loader/container.go
  bpf/loader/loader.go
  bpf/openssl.h
  bpf/openssl102a_arm64_bpfel.go
  bpf/openssl102a_x86_bpfel.go
  bpf/openssl110a_arm64_bpfel.go
  bpf/openssl110a_x86_bpfel.go
  bpf/openssl111a_arm64_bpfel.go
  bpf/openssl111a_x86_bpfel.go
  bpf/openssl111b_arm64_bpfel.go
  bpf/openssl111b_x86_bpfel.go
  bpf/openssl111d_arm64_bpfel.go
  bpf/openssl111d_x86_bpfel.go
  bpf/openssl111j_arm64_bpfel.go
  bpf/openssl111j_x86_bpfel.go
  bpf/openssl300_arm64_bpfel.go
  bpf/openssl300_x86_bpfel.go
  bpf/openssl310_arm64_bpfel.go
  bpf/openssl310_x86_bpfel.go
  bpf/openssl320_arm64_bpfel.go
  bpf/openssl320_x86_bpfel.go
  bpf/openssl323_arm64_bpfel.go
  bpf/openssl323_x86_bpfel.go
  bpf/openssl330_arm64_bpfel.go
  bpf/openssl330_x86_bpfel.go
  bpf/openssl340_arm64_bpfel.go
  bpf/openssl340_x86_bpfel.go
  bpf/pktlatency.bpf.c
  bpf/pktlatency.h
  bpf/types.go
  cmd/root.go
  common/net.go
  testdata/ipip_test.sh
  testdata/ipip_test3.sh
  testdata/ipip_test_clean.sh
Labels: enhancement, size:XXL

#256 feat: new version detection
  .goreleaser.yaml
  agent/agent.go
  cmd/version.go
  go.mod
  go.sum
  version/detect.go
  version/version.go
Labels: enhancement, size:L, lgtm

#259 fix(bpf/ssl): first HTTPS request on the server side might not be captured
  agent/analysis/stat.go
  agent/conn/conntrack.go
  agent/conn/first_packet_processor.go
  agent/conn/processor.go
  bpf/agent_arm64_bpfel.go
  bpf/agent_x86_bpfel.go
  bpf/data_common.h
  bpf/gen.go
  bpf/openssl.h
  bpf/pktlatency.bpf.c
  bpf/pktlatency.h
  docs/cn/debug-tips.md
  docs/cn/faq.md
  docs/cn/how-to-add-a-new-protocol.md
  docs/cn/json-output.md
  docs/cn/quickstart.md
  docs/cn/watch.md
  docs/debug-tips.md
  docs/faq.md
  docs/how-to-add-a-new-protocol.md
  docs/json-output.md
  docs/public/faq-time-detail.png
  docs/quickstart.md
  docs/watch.md
Labels: documentation, size:L, bug-fix

#264 test(e2e): add e2e test for sendfile & server side https
  agent/conn/conntrack.go
  testdata/nginx_https.conf
  testdata/test_https.sh
Labels: size:L

#268 refactor: optimize logs
  agent/agent.go
  agent/agent_test.go
  agent/agent_utils_test.go
  bpf/loader/loader.go
  bpf/prog.go
Labels: size:L

#273 fix: add check for AttrDataMemberLoc when val is []uint8
  agent/uprobe/dwarf_reader/buf.go
  agent/uprobe/dwarf_reader/reader.go
  agent/uprobe/gotls.go
  bpf/loader/loader.go
Labels: size:L, bug-fix

#274 fix: handle big syscall data (truncated) properly
  .github/workflows/test.yml
  agent/conn/conntrack.go
  agent/conn/processor.go
  agent/protocol/fakedata.go
  agent/protocol/http.go
  agent/protocol/http_test.go
  bpf/data_common.h
  testdata/test_truncated_data.sh
Labels: size:L

#276 feat: add an option to control whether to start gops for purpose of debugging
  agent/agent.go
  agent/common/options.go
  cmd/root.go
Labels: enhancement, size:XS

#277 feat: add options to control whether trace dev/socket/ssl events
  agent/agent.go
  agent/agent_utils_test.go
  agent/analysis/stat.go
  agent/common/options.go
  agent/render/watch/option.go
  agent/render/watch/time_detail.go
  agent/render/watch/watch_render.go
  bpf/loader/loader.go
  cmd/watch.go
  docs/cn/how-to.md
  docs/cn/watch.md
  docs/how-to.md
  docs/public/watch-result-detail-with-socket-event.jpg
  docs/public/watch-result-detail.jpg
  docs/public/watch-result.jpg
  docs/watch.md
Labels: enhancement, size:L

#278 feat: support trace socket event for ipv6
  agent/compatible/type.go
  bpf/agent_arm64_bpfel.go
  bpf/agent_x86_bpfel.go
  bpf/agentlagacykernel310_arm64_bpfel.go
  bpf/agentlagacykernel310_x86_bpfel.go
  bpf/loader/loader.go
  bpf/pktlatency.bpf.c
  testdata/test_ipv6.sh
Labels: enhancement, size:L

#280 refactor: change tcp seq type to uint32
  agent/buffer/stream_buffer.go
  agent/conn/conntrack.go
  agent/conn/kern_event_handler.go
  bpf/agent_arm64_bpfel.go
  bpf/agent_x86_bpfel.go
  bpf/data_common.h
  bpf/pktlatency.bpf.c
  bpf/pktlatency.h
  bpf/types.go
Labels: size:L

#281 fix: fix memory leak
  agent/analysis/stat.go
  agent/conn/kern_event_handler.go
  agent/conn/processor.go
  common/ringbuffer.go
  testdata/test_filter_by_l4.sh
Labels: size:L, bug-fix
